# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.1
_src_path: gh:algorandfoundation/algokit-python-template
author_email: upendra.singh@tesseris.org
author_name: upendrasingh
contract_name: hello_world
deployment_language: python
preset_name: starter
project_name: algo_hack

